#testing aws connection with my role
name: docker build and push
on:
  workflow_call:
    inputs: 
      image_tag: 
        required: true 
        type: string   # run manually from GitHub Actions tab

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download JAR artifacts
        uses: actions/download-artifact@v4 
        with: 
          name: app-jar 
          path: app
      - name: Show files
        run: ls -la app
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::207567756200:role/github_actions_access_to_aws_services   # <-- your role ARN
          aws-region: us-east-1
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3 
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t bank_app .
      - name: Tag Docker image
        run: docker tag myapp 207567756200.dkr.ecr.us-east-1.amazonaws.com/bank_app:latest
      - name: list images
        run: docker images
      - name: Push Docker image to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
            docker login --username AWS --password-stdin  207567756200.dkr.ecr.us-east-1.amazonaws.com
          docker push  207567756200.dkr.ecr.us-east-1.amazonaws.com/bank_app:latest

